import React from 'react';
import {
  AboutContainer,
  AboutTitle,
  BanerWraper,
  ImageCard,
  SpanClose,
  SpanTitle,
  TextMessinaBig,
  TextMessinaLitle,
} from './About.styled';
import { useMediaQuery } from 'react-responsive';
import Banner from './Banner';


const About: React.FC = () => {
  const isMobile = useMediaQuery({ query: '(max-width: 768px' });
  const isDesktop = useMediaQuery({ query: '(min-width: 1244px)' });
  const Break = () => <br />;

 

  return (
    <>
      <AboutContainer id="about">
        <AboutTitle>
          a Story that started with{' '}
          <SpanTitle>one simple{isMobile ?? <Break />} ape</SpanTitle>
        </AboutTitle>
        <TextMessinaBig>
          WHO GOT
          {isMobile ?? <Break />} FED UP WITH BORING AND HYPOCRITIC COMMONPLACE
          THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE
          {isMobile && <Break />}{isDesktop && <Break />} YACHT
        </TextMessinaBig>

        <TextMessinaLitle>
          <SpanClose>✖️</SpanClose>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY{isMobile && <Break />} USERS
        </TextMessinaLitle>
      </AboutContainer>
      <BanerWraper>
      <Banner/>
      <Banner/>
      </BanerWraper>
    </>
  );
};

export default About;
